### ISSUE TITLE
Github Repository Link Broken

### ISSUE THREAD

**Issue by pwintz** [mcrovella/CS132-Geometric-Algorithms#13]
The Github link at the top of each page doesn't do anything when I click it. 
![image](https://github.com/mcrovella/CS132-Geometric-Algorithms/assets/19618780/8268892b-4971-41d9-8bd1-e42da5df9456)

**Comment by pwintz** [comment]
Oh, I see what the problem is. I expected that clicking the icon would take me to GitHub but I actually needed to click the little "repository" dropdown that appears when hovering over the icon.

**Comment by mcrovella** [comment]
Closed.
