### ISSUE TITLE
Extra "$" signs in Orthogonality page 

### ISSUE THREAD

**Issue by pwintz** [mcrovella/CS132-Geometric-Algorithms#14]
On this page: https://www.cs.bu.edu/fac/crovella/cs132-book/L20Orthogonality.html
there are some extra dollar signs around one of the LaTeX equations:
![image](https://github.com/mcrovella/CS132-Geometric-Algorithms/assets/19618780/b04e42f3-bfa5-4fd1-aa00-0456efb7124f)

**Comment by mcrovella** [comment]
Thanks - fixed.
